services:
  django-server:
    build: ./django-server
    image: django-server
    container_name: django-server
    volumes:
      - django-data:/code
    ports:
      - 8000:8000
    networks:
      - devopsnet

  jenkins:
    build: ./jenkins
    image: jenkins
    container_name: jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - django-data:/deploy
    ports:
      - 8080:8080
    networks:
      - devopsnet

networks:
  devopsnet:
    driver: bridge

volumes:
  django-data:
  jenkins-data:
